### ISSUE TITLE
Crashes after connecting to ZEI

### ISSUE THREAD

**Issue by thomasphansen** [krisbuist/timeular-zei-linux#1] opened 2017-11-22 09:59 UTC
Hello,
I'm trying to use your solution, but it keeps on crashing (it actually seem to crash the entire BlueZ layer...).
### What I'm doing:
# sudo ./timeular-zei-linux-master
<and then click on the pairing button on ZEIo device)
### What I get:
    2017/11/22 10:07:49 Webserver started
    2017/11/22 10:07:50 API server authenticated
    2017/11/22 10:07:50 Activities loaded
    2017/11/22 10:07:50 Trying to connect to the ZEI
    2017/11/22 10:07:54 Connected to the ZEI
    2017/11/22 10:07:55 Device side: 0
    2017/11/22 10:07:55 Subscribed to ZEI side changes
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x407798]
    
    goroutine 70 [running]:
    panic(0x8221c0, 0xc82000a110)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
    main.main.func1(0x0)
        /home/thomas/projects/go/src/timeular-zei-linux-master/linux-zei.go:75 +0x8e8
    created by main.(*BluetoothManager).connectAndRun
        /home/thomas/projects/go/src/timeular-zei-linux-master/BluetoothManager.go:72 +0x8bf

### Error on dmesg:
    [  871.460495] blueman-manager[3570]: segfault at 19 ip 00007fd9cd7e77d0 sp 00007ffd48c58688 error 4 in libglib-2.0.so.0.4800.2[7fd9cd785000+10f000]

### Error in syslog:

    Nov 22 10:39:46 spy-thomas-desktop acpid: input device has been disconnected, fd 17
    Nov 22 10:39:46 spy-thomas-desktop NetworkManager[959]: <info>  [1511343586.2853] device (7C:01:91:71:16:B5): state change: disconnected -> unmanaged (reason 'removed') [30 10 36]
    Nov 22 10:39:46 spy-thomas-desktop NetworkManager[959]: <info>  [1511343586.3379] bluez: BT device iPhone de Thomas (7C:01:91:71:16:B5) added (NAP)
    Nov 22 10:39:46 spy-thomas-desktop bluetoothd[925]: Endpoint unregistered: sender=:1.46 path=/MediaEndpoint/A2DPSource
    Nov 22 10:39:46 spy-thomas-desktop bluetoothd[925]: Endpoint unregistered: sender=:1.46 path=/MediaEndpoint/A2DPSink
    Nov 22 10:39:46 spy-thomas-desktop NetworkManager[959]: <info>  [1511343586.3385] manager: (7C:01:91:71:16:B5): new Bluetooth device (/org/freedesktop/NetworkManager/Devices/6)
    Nov 22 10:39:46 spy-thomas-desktop NetworkManager[959]: <info>  [1511343586.3387] device (7C:01:91:71:16:B5): state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
    Nov 22 10:39:46 spy-thomas-desktop NetworkManager[959]: <info>  [1511343586.3391] device (7C:01:91:71:16:B5): state change: unavailable -> unmanaged (reason 'removed') [20 10 36]

(looks like these lines register the bluez going down, since my bt headphone (using A2DBSource) went down)

### My system:
    $ uname -a
    Linux spy-thomas-desktop 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	LinuxMint
    Description:	Linux Mint 18.2 Sonya
    Release:	18.2
    Codename:	sonya

    $ sudo lsusb -v
    (attached)
    
    $ lscpu
    (attached)

[lsusb.txt](https://github.com/krisbuist/timeular-zei-linux/files/1495435/lsusb.txt)
[lscpu.txt](https://github.com/krisbuist/timeular-zei-linux/files/1495442/lscpu.txt)

For now, I'm using the original ZEI application on a Windows VM, but I'd love to have it running only on pure linux...
Thank you for coding this, and thanks for any help you may provide!

**Comment by krisbuist** [comment] 2017-11-22 19:32
Hi,

Thanks for your detailed error report. I don't immediately see why this is crashing here, not sure if the root cause is in the bluez layer or in my code.

> looks like these lines register the bluez going down, since my bt headphone (using A2DBSource) went down

Did you try connecting to the Zei without any other device connected?
Also, could you try to bring the hci device down before starting the timeular-zei? f.e. `sudo hciconfig hci0 down`?

---

I'll try to reproduce and look into it somewhere in the next few days when I'll bring my Zei home :)

**Comment by krisbuist** [comment] 2017-12-01 09:58
It could very well be that I accidentally broke the Bluetooth connection in commit 19251b451ce7
Could you perhaps try to test against that commit on your machine?

**Comment by olivettiwetti** [comment] 2017-12-01 13:12
Interesting... I had the same issue on my Fedora 27 box. I had to build it as root, now it's starting up.. Great.

**Comment by krisbuist** [comment] 2017-12-01 13:26
That is interesting. Building as non-root and running as root doesn't work for you? Only building _and_ running as root?

**Comment by olivettiwetti** [comment] 2017-12-01 15:08
jep

**Comment by krisbuist** [comment] 2017-12-11 19:30
There was indeed some flawed logic in the code. Whenever the application was launched with the Zei positioned on a side with no registered, the application indeed crashes.

When you would launch the application with the Zei on a side which represents an activity, it didn't have this problem. Building as root is not ought to be necessary, but for running it still is.

I believe this is fixed with commit 053492b16fd
If you would have the time to verify this works for you?

**Comment by thomasphansen** [comment] 2018-01-30 14:13
It's working fine now! :) Thanks for the good work!

**Closed as completed** 2018-01-30 16:08 UTC
Labels: bug
